apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp    # Apply this servie to anmy pods which has the specific labels
  type: LoadBalancer    #specify the service type i.e ClusterIP or NodePort
  ports:
  - port: 8080  # Container port exposed
    targetPort: 80  # Pods port
    nodePort: 31200 #